_BASE_: "../Base-DiffusionDet.yaml"
PREVENT_WEIGHTS_LOADING: True
MODEL:
  BACKBONE:
    NAME: 'build_resnet_dino_fpn_backbone'
  META_ARCHITECTURE: 'FSDiffusionDet'
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 16
DATASETS:
  TRAIN: ("DOTA_train2017",)
  VAL: ("DOTA_val2017",)
  TEST:  ("DOTA_test2017",)
SOLVER:
  IMS_PER_BATCH: 32
  STEPS: (40000,)
  MAX_ITER: 75000
  # MAX_ITER: 20
  CHECKPOINT_PERIOD: 10000
  LR_SCHEDULER_NAME: 'WarmupCosineLR'
  BASE_LR: 1e-4
  BASE_LR_END: 1e-5
  WARMUP_ITERS: 500
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
# TRAIN_MODE: 'support_attention'
TRAIN_MODE: 'simplefs'
FINETUNE:
  MAX_ITER: 80000
TEST:
  EVAL_PERIOD: 500
# OUTPUT_DIR: 'runs/23-01-2023_17:23:02'
# OUTPUT_DIR: 'runs/07-02-2023_17:34:01'
FEWSHOT:
  ATTENTION:
    EXTRACT_EVERY: 10
    MAX_NUM_CLASSES: 3
  K_SHOT: 10
  BASE_SUPPORT: 'rng'

